version: "3.7"

services:
  my-backend:
    build: 
      context: .
      dockerfile: dockerfile
    
    ports:
      - 3000:3000
    env_file:
      - .env.docker

  my-mariadb:
    image: mariadb:latest
    environment:  # 올바른 키워드는 environment입니다.
      MARIADB_DATABASE: "crudproject"
      MARIADB_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306



